name: pokemon_app_global66
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^2.5.7
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/icons/
    - assets/images/logos/
